---
theme: light

server:
  address: 'tcp://0.0.0.0:9091'
  asset_path: /config/assets

log:
  level: info

totp:
  disable: false
  issuer: WB Digital

webauthn:
  disable: true

duo_api:
  disable: true

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: bcrypt
      bcrypt:
        cost: 12

access_control:
  default_policy: one_factor
  rules:
    - domain: 'auth.wbdigitalsolutions.com'
      policy: bypass
    - domain:
        - 'calendar-api.wbdigitalsolutions.com'
        - 'calendar-finances.wbdigitalsolutions.com'
        - 'calendar-health.wbdigitalsolutions.com'
        - 'agents.wbdigitalsolutions.com'
      policy: bypass
    - domain:
        - 'calendar.wbdigitalsolutions.com'
        - 'finances.wbdigitalsolutions.com'
        - 'health.wbdigitalsolutions.com'
        - 'calendar-langfuse.wbdigitalsolutions.com'
        - 'projects.wbdigitalsolutions.com'
      policy: one_factor

session:
  name: authelia_session
  cookies:
    - domain: 'wbdigitalsolutions.com'
      authelia_url: 'https://auth.wbdigitalsolutions.com'
      default_redirection_url: 'https://calendar.wbdigitalsolutions.com'
      expiration: 12h
      inactivity: 4h
      remember_me: 30d

storage:
  local:
    path: /data/db.sqlite3

notifier:
  filesystem:
    filename: /data/notification.txt

regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 5m
