package recurringtransaction

import (
	"testing"
	"time"

	"github.com/brunovieira/calendar-finances/internal/domain/transaction"
)

func onDay(day int) time.Time { return time.Date(2026, 9, day, 0, 0, 0, 0, time.UTC) }

func obligation() *RecurringTransaction {
	acc := "checking"
	return &RecurringTransaction{
		ProfileID:      "p1",
		BankAccountID:  &acc,
		Type:           "EXPENSE",
		Amount:         99,
		Description:    "Tim Celular",
		RecurrenceRule: "FREQ=MONTHLY;BYMONTHDAY=20",
		NextOccurrence: onDay(20),
		Status:         StatusActive,
	}
}

func payment(desc string, amount float64, day int) *transaction.Transaction {
	acc := "checking"
	return &transaction.Transaction{
		BankAccountID: acc,
		Type:          transaction.TypeExpense,
		Amount:        amount,
		Description:   desc,
		OccurredOn:    onDay(day),
		Status:        transaction.StatusConfirmed,
	}
}

// The amount is deliberately not compared: a phone bill quoted at 99 arrives at
// 111,57. Comparing it kept the obligation "pending" after it had been paid.
func TestIsSatisfiedBy_IgnoresTheAmount(t *testing.T) {
	if !obligation().IsSatisfiedBy(payment("Tim Celular", 111.57, 20)) {
		t.Fatal("a recurring bill paid at its real amount is satisfied")
	}
}

func TestIsSatisfiedBy_AcceptsAnotherDayInTheSameMonth(t *testing.T) {
	if !obligation().IsSatisfiedBy(payment("Tim Celular", 99, 1)) {
		t.Fatal("paid on the 1st for an obligation due on the 20th is still that month's payment")
	}
}

// A bill due at the end of a month is often paid in the first days of the next one.
func TestIsSatisfiedBy_AcceptsTheWindowAcrossMonths(t *testing.T) {
	obl := obligation()
	obl.NextOccurrence = time.Date(2026, 8, 30, 0, 0, 0, 0, time.UTC)

	if !obl.IsSatisfiedBy(payment("Tim Celular", 99, 3)) {
		t.Fatal("paid 4 days after it was due, in the next month, still satisfies it")
	}
}

func TestIsSatisfiedBy_RejectsADistantPayment(t *testing.T) {
	obl := obligation()
	obl.NextOccurrence = time.Date(2026, 7, 20, 0, 0, 0, 0, time.UTC)

	if obl.IsSatisfiedBy(payment("Tim Celular", 99, 20)) {
		t.Fatal("last month's obligation is not settled by this month's payment")
	}
}

func TestIsSatisfiedBy_RejectsAnotherBill(t *testing.T) {
	if obligation().IsSatisfiedBy(payment("Aluguel", 99, 20)) {
		t.Fatal("a different description is a different obligation")
	}
}

func TestIsSatisfiedBy_RejectsTheWrongAccount(t *testing.T) {
	tx := payment("Tim Celular", 99, 20)
	tx.BankAccountID = "other-account"

	if obligation().IsSatisfiedBy(tx) {
		t.Fatal("an obligation bound to an account is not settled from another one")
	}
}

func TestIsSatisfiedBy_RejectsTheOppositeDirection(t *testing.T) {
	tx := payment("Tim Celular", 99, 20)
	tx.Type = transaction.TypeIncome

	if obligation().IsSatisfiedBy(tx) {
		t.Fatal("income does not settle an expense obligation")
	}
}

func TestIsSatisfiedBy_RejectsACancelledTransaction(t *testing.T) {
	tx := payment("Tim Celular", 99, 20)
	tx.Status = transaction.StatusCancelled

	if obligation().IsSatisfiedBy(tx) {
		t.Fatal("a cancelled transaction settles nothing")
	}
}

// A scheduled-but-unpaid entry still counts: the obligation is already accounted for,
// so nagging about it again would be noise.
func TestIsSatisfiedBy_AcceptsAPlannedTransaction(t *testing.T) {
	tx := payment("Tim Celular", 99, 20)
	tx.Status = transaction.StatusPlanned

	if !obligation().IsSatisfiedBy(tx) {
		t.Fatal("an already-scheduled entry satisfies the obligation")
	}
}

// A transaction generated by this very recurrence carries its rule, so it matches even
// when someone renamed the description afterwards.
func TestIsSatisfiedBy_MatchesByRecurrenceRuleDespiteRename(t *testing.T) {
	tx := payment("TIM - conta de setembro", 111.57, 20)
	rule := "FREQ=MONTHLY;BYMONTHDAY=20"
	tx.RecurrenceRule = &rule

	if !obligation().IsSatisfiedBy(tx) {
		t.Fatal("the generated transaction carries the rule and should match")
	}
}

func TestIsDue_OnlyActiveObligationsThatAlreadyCameAround(t *testing.T) {
	obl := obligation()

	if !obl.IsDue(onDay(20)) {
		t.Error("an obligation due today is due")
	}
	if !obl.IsDue(onDay(25)) {
		t.Error("an overdue obligation is due")
	}
	if obl.IsDue(onDay(19)) {
		t.Error("an obligation that has not come around yet is not due")
	}

	obl.Status = StatusPaused
	if obl.IsDue(onDay(25)) {
		t.Error("a paused obligation is never due")
	}
}
